export const hamburguesas = [
  {id: 1, name: 'Apure'},
  {id: 2, name: 'Tasty'},
  {id: 3, name: 'Cinaruco'},
  {id: 4, name: 'Capanaparo'},
  {id: 5, name: 'Cunaviche'},
  {id: 6, name: 'Big Bora'},
  {id: 7, name: 'Arauca 2.0'},
  {id: 8, name: 'Street Bora'},
  {id: 9, name: 'Cheesburguer'},
  {id: 10, name: 'Nachos'},
  {id: 11, name: 'Orinoco'},
  {id: 12, name: 'Rustico de Pollo'},
  {id: 13, name: 'Caesar Chicken'},
  {id: 14, name: 'Crispy Deluxe'},
  {id: 15, name: 'Buffalo Ranch'},
  {id: 16, name: 'Classic Pulled Pork'},
  {id: 17, name: 'Bora Pulled Pork'},
  {id: 18, name: 'Cinnamon Pulled Pork'},
  {id: 19, name: 'Trio Bora'},
  {id: 20, name: 'Papas fritas'},
  {id: 21, name: 'Papas bora'},
  {id: 22, name: 'Pulled Pork Fries'},
  {id: 23, name: 'Ensalada Cesar'},
  {id: 24, name: 'Dedos mozzarella'},
  {id: 25, name: 'Tequeños'},
  {id: 26, name: 'Chicken Tenders'},
  {id: 27, name: 'Cajita Feliz'},
  {id: 28, name: 'Ensalada Capresa'},
  {id: 29, name: 'Aros de Cebolla'},
  {id: 30, name: 'Chicken Wings'},
  {id: 31, name: 'Hamburguesa de queso'},
  {id: 32, name: 'Smash Bora'},
  {id: 33, name: 'Resuelve tu almuerzo'},
]

export const tamanos = [
  {id: 1, name: 'Doble'},
  {id: 2, name: 'Clasica'},
  {id: 3, name: 'Junior'},
  {id: 4, name: 'Mini'},
  {id: 5, name: 'Individual'},
  {id: 6, name: 'Racion'},
  {id: 7, name: 'Mediana'},
  {id: 8, name: 'Grande'},
  {id: 9, name: '2 unidades'},
  {id: 10, name: '3 unidades'},
  {id: 11, name: '4 unidades'},
  {id: 12, name: '5 unidades'},
  {id: 13, name: '8 unidades'},
  {id: 14, name: '10 unidades'},
  {id: 15, name: '12 unidades'},
  {id: 16, name: '15 unidades'},
  {id: 17, name: '20 unidades'},
]

export const combos = ['10x15', '4x20', '5x25', '6x30', 'Trio de 4', 'Delta']
